from afs.exceptions.AfsError import AfsError

class VolError(AfsError):
    pass

    
